// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAirgPEgkxfmTiQyC00vcffu7bLU1WRBCM',
//     appId: '1:1067991317367:web:54fd1f21d82f160ec23f72',
//     messagingSenderId: '1067991317367',
//     projectId: 'mobocash-8bb25',
//     authDomain: 'mobocash-8bb25.firebaseapp.com',
//     storageBucket: 'mobocash-8bb25.appspot.com',
//     measurementId: 'G-TMH0TP5D3V',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBL5AXtrk9QKIuBvVXrYpRetUvzGqpGK10',
//     appId: '1:1067991317367:android:4f5099f29f39008cc23f72',
//     messagingSenderId: '1067991317367',
//     projectId: 'mobocash-8bb25',
//     storageBucket: 'mobocash-8bb25.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDxp1aLh8sy8M649-CptwLHjMuEpJAUKEk',
//     appId: '1:1067991317367:ios:e800d2bad3e84113c23f72',
//     messagingSenderId: '1067991317367',
//     projectId: 'mobocash-8bb25',
//     storageBucket: 'mobocash-8bb25.appspot.com',
//     iosClientId:
//         '1067991317367-6feaesledreqfkgcuq386eu5olat75bg.apps.googleusercontent.com',
//     iosBundleId: 'com.technonext.businesscard.businesscard',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDxp1aLh8sy8M649-CptwLHjMuEpJAUKEk',
//     appId: '1:1067991317367:ios:e800d2bad3e84113c23f72',
//     messagingSenderId: '1067991317367',
//     projectId: 'mobocash-8bb25',
//     storageBucket: 'mobocash-8bb25.appspot.com',
//     iosClientId:
//         '1067991317367-6feaesledreqfkgcuq386eu5olat75bg.apps.googleusercontent.com',
//     iosBundleId: 'com.technonext.businesscard.businesscard',
//   );
// }
